test_that("check_structure finds unparsable stuff", {
  test1 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet1")
  expect_error(check_structure_df(test1))
  test2 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet2")
  expect_true(check_structure_df(test2))
  test3 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet3")
  expect_error(check_structure_df(test3))
  test4 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet4")
  expect_error(check_structure_df(test4))
  test5 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet5")
  expect_true(check_structure_df(test5))
  test5 <- openxlsx::read.xlsx(test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet5")
  expect_true(check_structure_df(test5))
  expect_error(check_structure_wb(test_path("testdata", "struct_tests.xlsx")))
  expect_true(check_structure_wb(test_path("testdata", "struct_tests2.xlsx")))
  expect_message(message_structure(test_path("testdata", "struct_tests2.xlsx")))
  out <- message_structure(test_path("testdata", "struct_tests2.xlsx"))
  expect_equal(out[1,2], 2)
  expect_equal(out[1,3], 2)
  out <- message_structure(test_path("testdata", "struct_tests3.xlsx"))
  expect_equal(out[3,3], 4)
})
