dittodb::with_mock_db({
  con <- make_test_connection()

  test_that("prepare functions work", {

    x <- prepare_category_table("Maja Zalo\u017enik", con)
    expect_equal(dim(x), c(1,3))
    df <- openxlsx::read.xlsx(testthat::test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet14")
    x <- prepare_category_table_table(df, con, schema = "test_platform")
    expect_equal(dim(x), c(2,3))
    expect_equal(x[[2,3]], 122)
    x <- prepare_category_relationship_table("Maja Zalo\u017enik", con, schema = "test_platform")
    expect_equal(dim(x), c(1,3))
    out <- prepare_table_table(df, con, schema = "test_platform")
    expect_equal(dim(out), c(2,6))
    df <- openxlsx::read.xlsx(testthat::test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet17")
    out <- prepare_table_dimensions_table(df, con, schema = "test_platform")
    expect_equal(dim(out), c(6,3))
    expect_equal(out[[6,1]], "dim3")
    out <- prepare_dimension_levels_table(df, con,  schema = "test_platform")
    expect_equal(dim(out), c(10,3))
    df <- openxlsx::read.xlsx(testthat::test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet19")
    out <- prepare_series_table(df, con, schema = "test_platform")
    expect_equal(dim(out), c(2,5))
    df <- openxlsx::read.xlsx(testthat::test_path("testdata", "struct_tests.xlsx"), sheet = "Sheet34")
    out <- prepare_series_levels_table(df, con, schema = "test_platform")
    expect_equal(out[[1,2]], 452)
    out <- prepare_new_author_table("kh", "kjh", "ljlk", NA)
    expect_equal(out[1,3], "ljlk")
  })
})
